# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=1, default=0, max_digits=100)),
                ('time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=b'0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mps', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('count', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mps', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('count', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('mps', models.DecimalField(decimal_places=1, default=1, max_digits=100)),
                ('queued', models.BooleanField(default=0)),
                ('ready', models.BooleanField(default=0)),
                ('mPoints', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('mMps', models.DecimalField(decimal_places=1, default=1, max_digits=100)),
                ('canBuy', models.BooleanField(default=1)),
                ('time', models.IntegerField(default=0)),
                ('canClick', models.BooleanField(default=1)),
                ('timeClick', models.IntegerField(default=0)),
                ('first', models.BooleanField(default=0)),
                ('second', models.BooleanField(default=0)),
                ('third', models.BooleanField(default=0)),
                ('friends', models.ManyToManyField(related_name='_myuser_friends_+', to='savepablo.MyUser')),
                ('opponent', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='savepablo.MyUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='p1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='savepablo.MyUser'),
        ),
        migrations.AddField(
            model_name='game',
            name='p2',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='savepablo.MyUser'),
        ),
    ]
