# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='won',
            field=models.BooleanField(default=0),
        ),
    ]
